---
- name: Building a file from a JSON lookup
  hosts: planetexpress
  gather_facts: yes

  vars:
          issastros: "{{ lookup('url', 'http://api.open-notify.org/astros.json', split_lines=False) }}"

  tasks:
          ## Your job is to write one or two tasks
          ## that move the data contained in ISSASTROS
          ## and place in a file ~/isspassengers.txt
          ## on each of the remote hosts

          - name: Remote pretask
            file:
                    state: directory
                    path: ~/ans/output/
          
          - name: Display issastros
            debug:
                    var: issastros

          - name: Copy out content to a local file
            copy:
                    dest: ~/ans/output/isspassengers.txt
                    
                    content: "{{ issastros }}"

          ## if you finish the above challenge then...
          ## ONLY WRITE THE ASTROS NAMES into ~/issnames.txt
          ## on each remote hosts

          - name: Copy out content to a local file
            lineinfile:
              
              path: ~/ans/output/issnames.txt
              line : "{{ item.name.split()[0]}}"
              create: yes

            loop: "{{ issastros.people }}"

